name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Pull Docker image with tag
        run: |
          docker pull europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-preprod:${{ github.event.inputs.tag }}

      - name: Tag Docker image for production
        run: |
          docker tag europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-preprod:${{ github.event.inputs.tag }} europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-prod:${{ github.event.inputs.tag }}

      - name: Push Docker image to production
        run: |
          docker push europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-prod:${{ github.event.inputs.tag }}

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: "pokedevops"
          SERVICE_NAME: "service-student-amine-prod"
          REGION: "europe-west9"
          IMAGE: "europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-prod:${{ github.event.inputs.tag }}"
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
