name: Docker Pull, Tag, and Deploy

on:
  push:
    tags:
      - "*" # Trigger on all tags

jobs:
  pull-tag-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Configure docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Extract git commit SHA
        id: vars
        run: |
          COMMIT_ID=$(git rev-list -n 1 ${{ github.ref }})
          echo "::set-output name=commit_id::${COMMIT_ID}"
          echo "Commit ID: $COMMIT_ID"

      - name: Check if Docker image with commit ID exists
        run: |
          docker pull europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-dev:${{ steps.vars.outputs.commit_id }}
          # Check if the pull was successful or handle error

      - name: Tag Docker image with new tag
        run: |
          docker tag europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-dev:${{ steps.vars.outputs.commit_id }} europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-preprod:${{ github.ref_name }}

      - name: Push Docker image with new tag
        run: |
          docker push europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-preprod:${{ github.ref_name }}

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: "pokedevops"
          SERVICE_NAME: "service-student-amine-preprod"
          REGION: "europe-west9"
          IMAGE: "europe-west9-docker.pkg.dev/pokedevops/student-amine/service-student-amine-preprod:${{ github.ref_name }}"
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
